spring:
  application.name: gateway # for config server and service-registry
  config.import: "optional:configserver:"
  httpclient:
    ssl:
      useInsecureTrustManager: true
wavefront.application.name: spring-cloud-demo-tap

management:
  endpoint:
    restart.enabled: true
    gateway.enabled: true
  endpoints.web.exposure.include: "*"