#@ load("@ytt:data", "data")
product-service.product-names: VMware Tanzu for Kubernetes Operations, VMware Tanzu Application Platform
spring.security.oauth2.client.provider.appsso.issuer-uri: #@ data.values.issuer_uri
