apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: shipping-service
  labels:
    app.kubernetes.io/part-of: shipping-service
    apps.tanzu.vmware.com/workload-type: worker
    apps.tanzu.vmware.com/has-tests: 'true'
spec:
  params:
    - name: testing_pipeline_params
      value:
        source-sub-path: shipping-service
  build:
    env:
      - name: BP_JVM_VERSION
        value: '17'
  source:
    git:
      url: https://github.com/jianhuabi/spring-cloud-demo-tap.git
      ref:
        branch: main
    subPath: shipping-service
  serviceClaims:
    - name: rmq
      ref:
        apiVersion: rabbitmq.com/v1beta1
        kind: RabbitmqCluster
        name: rmq-1
    - name: config-server
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: configserver-binding-compatible
#  - name: observability
#    ref:
#      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
#      kind: ResourceClaim
#      name: observability-binding-compatible
#  - name: appsso-ca
#    ref:
#      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
#      kind: ResourceClaim
#      name: gateway-ca-extra-binding-compatible
